[ClassVersion("1.0.0.0"), FriendlyName("UpdateServicesServer")]
class DSC_UpdateServicesServer : OMI_BaseResource
{
    [Key, Description("An enumerated value that describes if WSUS is configured. Default value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to perform the initial configuration.")] String SetupCredential;
    [Write, Description("SQL Server for the WSUS database, omit for Windows Internal Database.")] String SQLServer;
    [Write, Description("Folder for WSUS update files. Set as empty string ('') to download from Microsoft Update.")] String ContentDir;
    [Write, Description("Join the Microsoft Update Improvement Program.")] Boolean UpdateImprovementProgram;
    [Write, Description("Upstream WSUS server, omit for Microsoft Update.")] String UpstreamServerName;
    [Write, Description("Port of upstream WSUS server.")] UInt16 UpstreamServerPort;
    [Write, Description("Use SSL with upstream WSUS server.")] Boolean UpstreamServerSSL;
    [Write, Description("Replica of upstream WSUS server.")] Boolean UpstreamServerReplica;
    [Write, Description("Proxy server to use when synchronizing, omit for no proxy.")] String ProxyServerName;
    [Write, Description("Proxy server port.")] UInt16 ProxyServerPort;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Proxy server credential, omit for anonymous.")] String ProxyServerCredential;
    [Read, Description("Proxy server credential username, in the format DOMAIN\\Username.")] String ProxyServerCredentialUsername;
    [Write, Description("Allow proxy server basic authentication.")] Boolean ProxyServerBasicAuthentication;
    [Write, Description("Updates are downloaded only when they are approved.")] Boolean DownloadUpdateBinariesAsNeeded;
    [Write, Description("Express installation packages should be downloaded.")] Boolean DownloadExpressPackages;
    [Write, Description("Update binaries are downloaded from Microsoft Update instead of from the upstream server.")] Boolean GetContentFromMU;
    [Write, Description("Update languages, * for all.")] String Languages[];
    [Write, Description("Update products, * for all.")] String Products[];
    [Write, Description("Update classifications, * for all.")] String Classifications[];
    [Write, Description("Synchronize automatically.")] Boolean SynchronizeAutomatically;
    [Write, Description("First synchronization. The value must be a string representation of a TimeSpan value. The valid range is 00:00:00 to 23:59:59 inclusive (as UTC).")] String SynchronizeAutomaticallyTimeOfDay;
    [Write, Description("Synchronizations per day. The valid range is 1 to 24 inclusive.")] UInt16 SynchronizationsPerDay;
    [Write, Description("Begin initial synchronization.")] Boolean Synchronize;
    [Write, Description("WSUS infrastructure updates are approved automatically.")] Boolean AutoApproveWsusInfrastructureUpdates;
    [Write, Description("The latest revision of an update should be approved automatically.")] Boolean AutoRefreshUpdateApprovals;
    [Write, Description("An update should be automatically declined when it is revised to be expired and AutoRefreshUpdateApprovals is enabled.")] Boolean AutoRefreshUpdateApprovalsDeclineExpired;
    [Write, Description("An enumerated value that describes how the Target Groups are populated. Default value is 'Client'."), ValueMap{"Client","Server"}, Values{"Client","Server"}] String ClientTargetingMode;
    [Write, Description("The downstream server should roll up detailed computer and update status information.")] Boolean DoDetailedRollup;
    [Write, Description("E-mail addresses of those to whom notification of new updates should be sent, omit for no notifications.")] String SyncNotificationRecipients[];
    [Write, Description("The frequency with which e-mail notifications should be sent.\nDaily {default}  \nWeekly   \n"), ValueMap{"Daily","Weekly"}, Values{"Daily","Weekly"}] String StatusNotificationFrequency;
    [Write, Description("The time of the day e-mail notifications should be sent. The value must be a string representation of a TimeSpan value. The valid range is 00:00:00 to 23:59:59 inclusive (as UTC).")] String StatusNotificationTimeOfDay;
    [Write, Description("E-mail addresses of those to whom update status notification should be sent, omit for no notifications.")] String StatusNotificationRecipients[];
    [Write, Description("E-mail language setting.")] String EmailLanguage;
    [Write, Description("The host name of the SMTP server.")] String SmtpHostName;
    [Write, Description("The port number of the SMTP server.")] UInt16 SmtpPort;
    [Write, Description("The display name of the e-mail sender.")] String SenderDisplayName;
    [Write, Description("The e-mail address of the sender.")] String SenderEmailAddress;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("The e-mail server credential, omit for anonymous.")] String EmailServerCredential;
    [Read, Description("The e-mail sender's username.")] String SmtpUserName;
    [Write, Description("Use Xpress Encoding to compress update metadata. Results in significant bandwidth savings, at the expense of some CPU overhead.")] Boolean IIsDynamicCompression;
    [Write, Description("Use foreground priority for BITS downloads to handle issues with proxy servers that do not correctly handle HTTP 1.1 range request.")] Boolean BitsDownloadPriorityForeground;
    [Write, Description("The maximum .cab file size (in megabytes) that Local Publishing will create.")] UInt32 LocalPublishingMaxCabSize;
    [Write, Description("The maximum number of concurrent update downloads.")] UInt32 MaxSimultaneousFileDownloads;
};
