[ClassVersion("1.0.0.0"), FriendlyName("UpdateServicesServer")]
class DSC_UpdateServicesServer : OMI_BaseResource
{
    [Key, Description("An enumerated value that describes if WSUS is configured.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to perform the initial configuration.")] String SetupCredential;
    [Write, Description("SQL Server for the WSUS database, omit for Windows Internal Database.")] String SQLServer;
    [Write, Description("Folder for WSUS update files.")] String ContentDir;
    [Write, Description("Join the Microsoft Update Improvement Program.")] Boolean UpdateImprovementProgram;
    [Write, Description("Upstream WSUS server, omit for Microsoft Update.")] String UpstreamServerName;
    [Write, Description("Port of upstream WSUS server.")] UInt16 UpstreamServerPort;
    [Write, Description("Use SSL with upstream WSUS server.")] Boolean UpstreamServerSSL;
    [Write, Description("Replica of upstream WSUS server.")] Boolean UpstreamServerReplica;
    [Write, Description("Proxy server to use when synchronizing, omit for no proxy.")] String ProxyServerName;
    [Write, Description("Proxy server port.")] UInt16 ProxyServerPort;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Proxy server credential, omit for anonymous.")] String ProxyServerCredential;
    [Read, Description("Proxy server credential username.")] String ProxyServerCredentialUsername;
    [Write, Description("Allow proxy server basic authentication.")] Boolean ProxyServerBasicAuthentication;
    [Write, Description("Update languages, * for all.")] String Languages[];
    [Write, Description("Update products, * for all.")] String Products[];
    [Write, Description("Update classifications, * for all.")] String Classifications[];
    [Write, Description("Synchronize automatically.")] Boolean SynchronizeAutomatically;
    [Write, Description("First synchronization.")] String SynchronizeAutomaticallyTimeOfDay;
    [Write, Description("Synchronizations per day.")] UInt16 SynchronizationsPerDay;
    [Write, Description("Begin initial synchronization.")] Boolean Synchronize;
    [write, Description("An enumerated value that describes if how the Target Groups are populated.\nClient {default}  \nServer   \n"), ValueMap{"Client","Server"}, Values{"Client","Server"}] String ClientTargetingMode;
};
