[ClassVersion("1.0.0.0"), FriendlyName("UpdateServicesCleanup")]
class MSFT_UpdateServicesCleanup : OMI_BaseResource
{
    [Key, Description("An enumerated value that describes if the WSUS cleanup task exists.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Decline updates that have not been approved fo 30 days or more, are not currently needed by any clients, and are superseded by an approved update.")] Boolean DeclineSupersededUpdates;
    [Write, Description("Decline updates that aren't approved and have been expired by Microsoft.")] Boolean DeclineExpiredUpdates;
    [Write, Description("Delete updates that are expired and have not been approved for 30 days or more, and delete older update revisions that have not been approved for 30 days or more.")] Boolean CleanupObsoleteUpdates;
    [Write, Description("Compress updates.")] Boolean CompressUpdates;
    [Write, Description("Delete computers that have not contacted the server in 30 days or more.")] Boolean CleanupObsoleteComputers;
    [Write, Description("Delete update files that aren't needed by updates or downstream servers.")] Boolean CleanupUnneededContentFiles;
    [Write, Description("Cleanup local published content files.")] Boolean CleanupLocalPublishedContentFiles;
    [Write, Description("Time of day to start cleanup.")] String TimeOfDay;
};
