# Localized Strings for UpdateServicesServer resource
ConvertFrom-StringData @'
TestFailedAfterSet      = Test-TargetResource returned false after calling set.
GettingWsusServer       = Getting WSUS server.
GetWsusServerFailed     = Get-WsusServer failed to return a WSUS Server. The server may not yet have been configured.
WSUSConfigurationFailed = WSUS configuration failed.
WsusEnsureValue         = WSUS server is {0}.
GettingWsusConfig       = Getting WSUS server configuration.
GettingWsusDatabaseConfig = Getting WSUS server database configuration.
GettingWsusSubscription = Getting WSUS server subscription.
GettingWsusEmailNotificationConfig = Getting WSUS server email notification configuration.
GettingWsusSQLServer    = Getting WSUS SQL server.
SQLServerName           = WSUS Server SQL Server is {0}.
GetWsusImproveProgram   = Getting WSUS Server update improvement program.
ImprovementProgram      = WSUS Server content update improvement program is {0}.
GetUpstreamServer       = Getting WSUS upstream server.
UpstreamServer          = WSUS Server upstream server is {0}, port {1}, use SSL {2}.
GetReplicaServer        = Getting WSUS replica server.
ReplicaServer           = WSUS Server replica server is {0}.
GetWsusProxyServer      = Getting WSUS Server proxy server.
WsusProxyServer         = WSUS Server proxy server is {0}, port {1}, user name {2}, basic authentication {3}.
GettingWsusUpdateFiles  = Getting WSUS Server update files.
WsusUpdateFiles         = WSUS Server update files is content directory {0}, download binaries as needed {1}, download express packages {2}, get content from Microsoft Update {3}.
GettingWsusLanguage     = Getting WSUS Server languages.
WsusLanguages           = WSUS Server languages are {0}.
GettingWsusClassifications = Getting WSUS Server Classifications.
WsusClassifications     = WSUS Server Classifications are {0}.
GettingWsusProducts     = Getting WSUS Server products.
WsusProducts            = WSUS Server products are {0}.
GettingWsusAdvancedAutomaticApprovals = Getting WSUS Server advanced automatic approvals.
WsusAutoApproveWsusInfrastructureUpdates = WSUS Server auto approve WSUS infrastructure updates is {0}.
WsusAutoRefreshUpdateApprovals = WSUS Server auto refresh update approvals is {0}.
WsusAutoRefreshUpdateApprovalsDeclineExpired = WSUS server auto decline when revised update is expired is {0}.
GettingWsusSyncConfig   = Getting WSUS Server synchronization settings.
WsusSyncAuto            = WSUS Server synchronize automatically is {0}.
WsusSyncAutoTimeOfDay   = WSUS Server synchronize automatically time of day is {0} (as UTC).
WsusSyncPerDay          = WSUS Server number of synchronizations per day is {0}.
GettingWsusTargetingMode = Getting WSUS Server targeting mode.
WsusClientTargetingMode = WSUS Server client targeting mode is {0}.
GettingWsusReportingRollup = Getting WSUS Server reporting rollup.
WsusDoDetailedRollup    = WSUS Server downstream server rollup is {0}.
GettingWsusEmailNotifications = Getting WSUS Server E-mail Notifications.
WsusSyncNotification    = WSUS Server e-mail sync notification recipients are {0}.
WsusStatusNotification  = WSUS Server e-mail status notification frequency is {0}, time of day {1} (as UTC), recipients {2}.
WsusEmailLanguage       = WSUS Server e-mail language is {0}.
WsusSmtpHostName        = WSUS Server e-mail SMTP host name is {0}.
WsusSmtpPort            = WSUS Server e-mail SMTP port is {0}.
WsusSenderDisplayName   = WSUS Server e-mail sender display name is {0}.
WsusSenderEmailAddress  = WSUS Server e-mail sender address is {0}.
WsusSmtpServerUserName  = WSUS Server e-mail SMTP server user name is {0}.
GettingWsusIIsDynamicCompression = Getting WSUS Server IIS dynamic compression.
IIsDynamicCompression   = WSUS Server IIS dynamic compression is {0}.
GettingWsusBitsDownloadPriorityForeground = Getting WSUS Server BITS download priority foreground.
BitsDownloadPriorityForeground = WSUS Server BITS download priority foreground is {0}.
GettingWsusLocalPublishingMaxCabSize = Getting WSUS Server local publishing max CAB size.
WsusLocalPublishingMaxCabSize = WSUS Server local publishing max CAB size is {0}.
GettingWsusMaxSimultaneousFileDownloads = Getting WSUS Server max simultaneous file downloads.
WsusMaxSimultaneousFileDownloads = WSUS Server max simultaneous file downloads is {0}.
RunningWsusPostInstall  = Running WSUS Post Install tasks.
ResolveWsusUtilExePath  = WsusUtil.exe path is {0}.
WsusUtilArgs            = WsusUtil.exe {0}.
ConfiguringWsus         = Configuring WSUS.
CheckPreviousConfig     = Check for previous configuration change.
ConfiguringUpdateImprove = Configuring WSUS Update Improvement Program.
ConfiguringUpstreamServer = Configuring WSUS Upstream Server.
ConfiguringWsusMsftUpdates = Configuring WSUS for Microsoft Update.
ConfiguringUpstreamServerReplica = Configuring WSUS Upstream Server Replica.
ConfiguringNoUpstreamServerReplica = Configuring WSUS No Upstream Server Replica.
ConfiguringWsusProxy    = Configuring WSUS proxy server.
ConfiguringProxyCred    = Configuring WSUS proxy server credential.
RemovingProxyCred       = Removing WSUS proxy server credential.
ConfiguringNoProxy      = Configuring WSUS no proxy server.
ConfiguringUpdateFiles  = Configuring WSUS Update Files.
ConfiguringHostMUStore = Configuring WSUS to host binaries on Microsoft Update.
ConfiguringDownloadUpdateBinariesAsNeeded = Configuring WSUS download binaries as needed.
ConfiguringDownloadExpressPackages = Configuring WSUS download express packages.
ConfiguringGetContentFromMU = Configuring WSUS get content from Microsoft Update.
ConfiguringLanguages    = Setting WSUS languages.
ConfiguringAutoApproveWsusInfrastructureUpdates = Configuring WSUS auto approve WSUS infrastructure updates.
ConfiguringAutoRefreshUpdateApprovals = Configuring WSUS auto refresh update approvals.
ConfiguringAutoRefreshUpdateApprovalsDeclineExpired = Configuring WSUS auto decline when revised update is expired.
ConfiguringClientTargetMode = Configuring WSUS client targeting mode.
ConfiguringReportingRollup = Configuring WSUS reporting rollup.
ConfiguringSyncNotificationRecipients = Configuring WSUS e-mail sync notification recipients.
ConfiguringNoSyncNotificationRecipients = Configuring WSUS no e-mail sync notification recipients.
ConfiguringStatusNotificationRecipients = Configuring WSUS e-mail status notification recipients.
ConfiguringStatusNotificationFrequency = Configuring WSUS e-mail status notification frequency.
ConfiguringStatusNotificationTimeOfDay = Configuring WSUS e-mail status notification time of day.
ConfiguringNoStatusNotificationRecipients = Configuring WSUS no e-mail status notification recipients.
ConfiguringEmailLanguage = Configuring WSUS e-mail language.
UnsupportedEmailLanguage = Unsupported email language specified {0}.
ConfiguringSmtpHostName = Configuring SMTP host name and port.
ConfiguringSenderEmailAddress = Configuring SMTP sender email address.
ConfiguringSenderDisplayName = Configuring SMTP sender display name.
ConfiguringEmailServerCredential = Configuring WSUS e-mail server credential.
RemovingEmailServerCredential = Removing WSUS e-mail server credential.
ConfiguringIIsDynamicCompression = Configuring IIS dynamic compression.
ConfiguringBitsDownloadPriorityForeground = Configuring BITS download priority foreground.
ConfiguringLocalPublishing = Configuring local publishing.
ConfiguringMaxSimultaneousFileDownloads = Configuring max simultaneous file downloads
RemovingDefaultProductsInit = Removing default products before initial sync.
RemovingDefaultClassificationsInit = Removing default classifications before initial sync.
RunningInitSync         = Running WSUS initial synchronization online.
InitSyncSuccess         = Initial WSUS synchronization succeeded.
InitSyncFailure         = Initial WSUS synchronization failed.
RunningInitOfflineSync  = Running WSUS initial synchronization offline.
ConfiguringProducts     = Setting WSUS products.
ConfiguringAllProducts  = Configure all product for subscription.
ConfiguringWildcardProducts = Configuring products for wilcard expression product : {0}
NoWildcardProductFound  = No products found for wildcard expression product.
ConfiguringNameProduct  = Configuring products for product name : {0}
NoNameProductFound      = No product found for product name.
ConfiguringClassifications = Setting WSUS classifications.
ClassificationNotFound  = Classification {0} not found.
ConfiguringSyncSchedule = Setting WSUS synchronization schedule.
ConfiguringSyncTimeOfDay = Setting WSUS synchronization time of day.
ConfiguringSyncPerDay   = Setting number of WSUS synchronizations per day.
SynchronizingWsus       = Synchronizing WSUS.
EnsureTestFailed        = Ensure test failed.
ImproveProgramTestFailed = Update Improvement Program test failed.
UpstreamNameTestFailed  = Upstream Server Name test failed.
UpstreamPortTestFailed  = Upstream Server Port test failed.
UpstreamSSLTestFailed   = Upstream Server SSL test failed.
UpstreamReplicaTestFailed = Upstream Server Replica test failed.
NoUpstreamServerReplicaTestFailed = No Upstream Server Replica test failed.
ProxyNameTestFailed     = Proxy Server Name test failed.
ProxyPortTestFailed     = Proxy Server Port test failed.
ProxyCredTestFailed     = Proxy Server Credential test failed - incorrect credential.
ProxyBasicAuthTestFailed = Proxy Server Basic Authentication test failed.
ProxyCredSetTestFailed  = Proxy Server Credential test failed - credential set.
ContentDirTestFailed    = Content dir test failed.
UpdateFilesDownloadUpdateBinariesTestFailed = Update Files download update binaries as needed test failed.
UpdateFilesDownloadExpressPackagesTestFailed = Update Files download express packages test failed.
UpdateFilesGetContentFromMUTestFailed = Update Files get content from Microsoft Update test failed.
UpdateFilesAutoApproveWsusInfraTestFailed = Update Files auto approve WSUS infrastructure updates test failed.
UpdateFilesAutoRefreshUpdateApprovalsTestFailed = Update Files auto refresh update approvals test failed.
UpdateFilesAutoDeclineExpiredTestFailed = Update Files auto refresh update approvals decline expired test failed.
SyncNotificationRecipientsTestFailed = Sync notification recipients test failed.
StatusNotificationRecipientsTestFailed = Status notification recipients test failed.
StatusNotificationFrequencyTestFailed = Status notification frequency test failed.
StatusNotificationTimeOfDayTestFailed = Status notification time of day test failed.
EmailLanguageTestFailed = Email language test failed.
SmtpHostNameTestFailed  = SMTP host name test failed.
SmtpPortTestFailed      = SMTP port test failed.
SenderDisplayNameTestFailed = Sender display name test failed.
SenderEmailAddressTestFailed = Sender e-mail address test failed.
EmailServerCredTestFailed = E-mail server Credential test failed - incorrect credential.
IIsDynamicCompressionTestFailed = IIS dynamic compression test failed.
BitsDownloadPriorityForegroundTestFailed = BITS download priority foreground test failed.
LocalPublishingMaxCabSizeTestFailed = Local publishing max CAB size test failed.
MaxSimultaneousFileDownloadsTestFailed = Max simultaneous file downloads test failed.
LanguageAsStrTestFailed = Languages test failed (evaluated as single string).
LanguageSetTestFailed   = Languages test failed.
TestGetWsusServer       = Test Products failed, no WSUS Server found.
GetAllProductForTest    = Getting all products.
GetWildCardProductForTest = Getting all products based on wildcard : {0}
GetNameProductForTest   = Getting products based on name : {0}
ProductTestFailed       = Products test failed.
ClassificationsTestFailed = Classifications test failed.
SyncAutomaticallyTestFailed = Synchronize Automatically test failed.
SyncTimeOfDayTestFailed = Synchronize Automatically Time Of Day test failed.
SyncPerDayTestFailed     = Synchronizations Per Day test failed.
ClientTargetingModeTestFailed = Client Targeting Mode test failed.
ReportingRollupDoDetailedRollupTestFailed = Reporting rollup do detailed rollup test failed.
SavingWSUSConfiguration = Attempting to save WSUS configuration - attempt {0}.
FailedToSaveWSUSConfiguration = Failed to save WSUS configuration after {0} attempts.
'@
